name: Build Debug Apk

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Apk
        shell: bash {0}
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug
      - name: Upload Apk file
        uses: actions/upload-artifact@v2
        with:
          name: ppqr-app-debug
          path: app/build/outputs
